### ISSUE TITLE
Add command to list the top five linux processes

### ISSUE THREAD

**Issue by JeffResc** [JeffResc/DiscordServerManagementBot#1]
Add command to list the top five Linux processes as [described here on StackOverflow](https://unix.stackexchange.com/questions/13968/show-top-five-cpu-consuming-processes-with-ps). This should be relatively easy for someone with Node.js and Linux Server knowledge. This module should be added to [the modules directory](https://github.com/JeffResc/DiscordServerManagementBot/tree/master/modules) and activated by default in [the config](https://github.com/JeffResc/DiscordServerManagementBot/tree/master/config.js#L11). Please reply if you'd like to be assigned to this issue.

**Comment by lucasrabiec** [comment]
PR: https://github.com/JeffResc/DiscordServerManagementBot/pull/4

**Comment by JeffResc** [comment]
Thanks for the PR, I've merged it and ready for you to rebase.

**Comment by lucasrabiec** [comment]
@JeffResc you already merged it so there is no need to rebasing :+1:
