### ISSUE TITLE
Add a basic how-to in the README file

### ISSUE THREAD

**Issue by JeffResc** [JeffResc/DiscordServerManagementBot#2]
Add a basic how-to in the README file that shows the user how to configure the bot in the [config.js file](https://github.com/JeffResc/DiscordServerManagementBot/blob/master/config.js). If you read through the [config.js file](https://github.com/JeffResc/DiscordServerManagementBot/blob/master/config.js), finding out how to write this in the README should be a relatively easy task.

**Comment by lucasrabiec** [comment]
I added PR: https://github.com/JeffResc/DiscordServerManagementBot/pull/3

**Comment by JeffResc** [comment]
Thanks, accepted and merged. :)
