### ISSUE TITLE
Fix Travis-CI Syntax Errors

### ISSUE THREAD

**Issue by JeffResc** [JeffResc/DiscordServerManagementBot#5]
[Our Travis-CI Tests](https://travis-ci.org/JeffResc/DiscordServerManagementBot/jobs/595382254) hold some syntax errors throughout the project that mostly consist of semi-colons. This task should be relatively easy for beginners as it mostly consists of fixing semicolons at the given locations in the log. Please reply if you’d be interested in working on this issue.

**Comment by jonathan-sh** [comment]
@JeffResc I would like do this.

**Comment by jonathan-sh** [comment]
PR #6 

I added it to my personal Travis account to test this task. Please, check here: [travis-log](https://travis-ci.org/jonathan-sh/DiscordServerManagementBot/jobs/595410938)

[![Build Status](https://travis-ci.org/jonathan-sh/DiscordServerManagementBot.svg?branch=master)](https://travis-ci.org/jonathan-sh/DiscordServerManagementBot)

**Comment by JeffResc** [comment]
Thanks so much, @jonathan-sh. Looks great!
